import {
    LayoutDashboard,
    Receipt,
    RefreshCcw,
    Download,
    Users,
    ShoppingCart,
    CreditCard,
    Truck,
    Warehouse,
    Layers,
    Package,
    ClipboardList,
    ArrowRightLeft,
    Activity,
    BookOpen,
    Landmark,
    Wallet,
    CheckCircle,
    FileText,
    ShieldAlert,
    ScrollText,
    Lock,
    UserCog,
    Briefcase,
    PieChart,
    ArrowUpDown,
    DollarSign,
    TrendingUp,
    TrendingDown,
    FileBarChart2,
    Settings,
    Tag,
    Clock,
    AlertTriangle,
    QrCode,
} from 'lucide-react';

export const navSections = [
    {
        title: 'الرئيسية',
        icon: LayoutDashboard,
        featureKey: 'dashboard',
        isStandalone: true,
        href: '/',
        links: [
            { id: '/', href: '/', label: 'لوحة التحكم' }
        ],
    },
    // ═══════════════════════════════════════════════════════
    // 🍽️  أقسام المطاعم والكافيهات (تظهر فقط لنشاط RESTAURANTS)
    // ═══════════════════════════════════════════════════════
    {
        title: 'نقطة البيع (POS)',
        icon: Receipt,
        featureKey: 'pos',
        links: [
            { id: '/pos', href: '/pos', label: 'شاشة الكاشير' },
            { id: '/pos/history', href: '/pos/history', label: 'سجل الطلبات' },
        ],
    },
    {
        title: 'الطاولات والصالة',
        icon: Layers,
        featureKey: 'tables',
        links: [
            { id: '/tables', href: '/tables', label: 'خريطة الطاولات' },
            { id: '/shifts', href: '/shifts', label: 'الورديات' },
        ],
    },
    {
        title: 'المطبخ والوصفات',
        icon: ClipboardList,
        featureKey: 'kitchen',
        links: [
            { id: '/kitchen', href: '/kitchen', label: 'شاشة المطبخ (KDS)' },
            { id: '/recipes', href: '/recipes', label: 'وصفات الطبخ' },
            { id: '/modifiers', href: '/modifiers', label: 'الإضافات والتعديلات' },
        ],
    },
    {
        title: 'التوصيل',
        icon: Truck,
        featureKey: 'delivery',
        links: [
            { id: '/delivery', href: '/delivery', label: 'طلبات التوصيل' },
        ],
    },
    {
        title: 'باركود وQR الطاولات',
        icon: QrCode,
        featureKey: 'barcode',
        links: [
            { id: '/barcode', href: '/barcode', label: 'QR الطاولات' },
        ],
    },
    {
        title: 'المبيعات',
        icon: Receipt,
        featureKey: 'sales',
        links: [
            { id: '/quotations', href: '/quotations', label: 'عروض الأسعار' },
            { id: '/sales', href: '/sales', label: 'فواتير المبيعات' },
            { id: '/sale-returns', href: '/sale-returns', label: 'مرتجع مبيعات' },
            { id: '/receipts', href: '/receipts', label: 'سندات القبض' },
            { id: '/customers', href: '/customers', label: 'العملاء' },
            { id: '/settlements', href: '/settlements', label: 'تسوية ديون (حوالة)' },
        ],
    },
    {
        title: 'الأقساط',
        icon: CreditCard,
        featureKey: 'installments',
        links: [
            { id: '/installments', href: '/installments', label: 'خطط التقسيط' },
            { id: '/due-installments', href: '/due-installments', label: 'الأقساط المستحقة' },
            { id: '/overdue-installments', href: '/overdue-installments', label: 'المتأخرات' },
        ],
    },
    {
        title: 'المشتريات',
        icon: ShoppingCart,
        featureKey: 'purchases',
        links: [
            { id: '/purchases', href: '/purchases', label: 'فواتير المشتريات' },
            { id: '/purchase-returns', href: '/purchase-returns', label: 'مرتجع مشتريات' },
            { id: '/purchase-payments', href: '/purchase-payments', label: 'سندات الصرف' },
            { id: '/suppliers', href: '/suppliers', label: 'الموردين' },
        ],
    },
    {
        title: 'إدارة المخزون',
        icon: Warehouse,
        featureKey: 'inventory',
        links: [
            { id: '/units', href: '/units', label: 'الوحدات' },
            { id: '/categories', href: '/categories', label: 'التصنيفات' },
            { id: '/items', href: '/items', label: 'الأصناف' },
            { id: '/warehouses', href: '/warehouses', label: 'المخازن' },
            { id: '/stocktakings', href: '/stocktakings', label: 'جرد المخازن' },
            { id: '/warehouse-transfers', href: '/warehouse-transfers', label: 'التحويل بين المخازن' },
        ],
    },
    {
        title: 'الحسابات العامة',
        icon: BookOpen,
        featureKey: 'accounting',
        links: [
            { id: '/accounts', href: '/accounts', label: 'شجرة الحسابات' },
            { id: '/opening-balances', href: '/opening-balances', label: 'الأرصدة الافتتاحية' },
            { id: '/financial-years', href: '/financial-years', label: 'السنة المالية' },
        ],
    },
    {
        title: 'الخزن والبنوك',
        icon: Landmark,
        featureKey: 'treasury',
        links: [
            { id: '/treasuries', href: '/treasuries', label: 'الخزن والبنوك' },
            { id: '/other-income', href: '/other-income', label: 'الإيرادات' },
            { id: '/expenses', href: '/expenses', label: 'المصروفات' },
        ],
    },
    {
        title: 'القيود',
        icon: FileText,
        featureKey: 'accounting',
        links: [
            { id: '/cost-centers', href: '/cost-centers', label: 'مراكز التكلفة' },
            { id: '/journal-entries', href: '/journal-entries', label: 'القيود اليومية' },
            { id: '/closing-entries', href: '/closing-entries', label: 'قيود الإقفال' },
        ],
    },
    {
        title: 'الموارد البشرية',
        icon: UserCog,
        featureKey: 'hr',
        links: [
            { id: '/employees', href: '/employees', label: 'الموظفين' },
            { id: '/payrolls', href: '/payrolls', label: 'مسير الرواتب' },
            { id: '/advances', href: '/advances', label: 'السلف' },
            { id: '/deductions', href: '/deductions', label: 'الخصومات والجزاءات' },
            { id: '/departments', href: '/departments', label: 'الأقسام والوظائف' },
        ],
    },
    {
        title: 'الشركاء',
        icon: Briefcase,
        featureKey: 'partners',
        links: [
            { id: '/partners', href: '/partners', label: 'بيانات الشركاء' },
            { id: '/partner-accounts', href: '/partner-accounts', label: 'حسابات الشركاء' },
            { id: '/profit-distribution', href: '/profit-distribution', label: 'توزيع الأرباح' },
            { id: '/capital', href: '/capital', label: 'رأس المال' },
        ],
    },
    {
        title: 'الأصول الثابتة',
        icon: Landmark,
        featureKey: 'fixed_assets',
        links: [
            { id: '/fixed-assets', href: '/fixed-assets', label: 'إدارة الأصول' },
            { id: '/fixed-assets/depreciation', href: '/fixed-assets/depreciation', label: 'الإهلاك' },
            { id: '/fixed-assets/disposals', href: '/fixed-assets/disposals', label: 'مبيعات وخردة الأصول' },
        ],
    },
    {
        title: 'التقارير الإحصائية',
        icon: PieChart,
        featureKey: 'reports',
        isStandalone: true,
        href: '/reports',
        links: [
            { id: 'reports-financial', href: '/reports', label: 'التقارير المالية' },
            { id: 'reports-sales-purchases', href: '/reports', label: 'المبيعات والمشتريات' },
            { id: 'reports-inventory', href: '/reports', label: 'تقارير المخزون' },
            { id: 'reports-partners', href: '/reports', label: 'العملاء والموردين' },
            { id: 'reports-treasury-bank', href: '/reports', label: 'الخزن والبنوك' },
            { id: 'reports-hr', href: '/reports', label: 'تقارير الموظفين' },
            { id: 'reports-installments', href: '/reports/installments', label: 'تقارير الأقساط' },
        ],
    },
    {
        title: 'إعدادات النظام',
        icon: Settings,
        featureKey: 'settings',
        isStandalone: true,
        href: '/settings',
        links: [
            { id: '/settings/company', href: '/settings', label: 'بيانات الشركة' },
            { id: '/settings/general', href: '/settings', label: 'الإعدادات العامة' },
            { id: '/settings/notifications', href: '/settings', label: 'الإشعارات' },
            { id: '/settings/users', href: '/settings', label: 'المستخدمين والصلاحيات' },
            { id: '/settings/subscription', href: '/settings', label: 'الاشتراك والخطة' },
            { id: '/settings/database', href: '/settings', label: 'قواعد البيانات' },
        ],
    },

];
